// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Octokit.Client.Marketplace_listing.Plans.Item.Accounts {
    public enum GetSortQueryParameterType {
        [EnumMember(Value = "created")]
        Created,
        [EnumMember(Value = "updated")]
        Updated,
    }
}
