// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Orgs.Item.CodeSecurity.Configurations
{
    /// <summary>The type of the bypass reviewer</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public enum ConfigurationsPostRequestBody_secret_scanning_delegated_bypass_options_reviewers_reviewer_type
    {
        [EnumMember(Value = "TEAM")]
        #pragma warning disable CS1591
        TEAM,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROLE")]
        #pragma warning disable CS1591
        ROLE,
        #pragma warning restore CS1591
    }
}
