// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Orgs.Item.CodeSecurity.Configurations.Item
{
    /// <summary>The enablement status of Dependabot security updates</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public enum WithConfiguration_PatchRequestBody_dependabot_security_updates
    {
        [EnumMember(Value = "enabled")]
        #pragma warning disable CS1591
        Enabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "disabled")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_set")]
        #pragma warning disable CS1591
        Not_set,
        #pragma warning restore CS1591
    }
}
