// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace GitHub.Orgs.Item.CodeSecurity.Configurations.Item {
    #pragma warning disable CS1591
    public class WithConfiguration_PatchRequestBody : IParsable 
    #pragma warning restore CS1591
    {
        /// <summary>The enablement status of GitHub Advanced Security</summary>
        public WithConfiguration_PatchRequestBody_advanced_security? AdvancedSecurity { get; set; }
        /// <summary>The enablement status of code scanning default setup</summary>
        public WithConfiguration_PatchRequestBody_code_scanning_default_setup? CodeScanningDefaultSetup { get; set; }
        /// <summary>The enablement status of Dependabot alerts</summary>
        public WithConfiguration_PatchRequestBody_dependabot_alerts? DependabotAlerts { get; set; }
        /// <summary>The enablement status of Dependabot security updates</summary>
        public WithConfiguration_PatchRequestBody_dependabot_security_updates? DependabotSecurityUpdates { get; set; }
        /// <summary>The enablement status of Dependency Graph</summary>
        public WithConfiguration_PatchRequestBody_dependency_graph? DependencyGraph { get; set; }
        /// <summary>A description of the code security configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The name of the code security configuration. Must be unique within the organization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The enablement status of private vulnerability reporting</summary>
        public WithConfiguration_PatchRequestBody_private_vulnerability_reporting? PrivateVulnerabilityReporting { get; set; }
        /// <summary>The enablement status of secret scanning</summary>
        public WithConfiguration_PatchRequestBody_secret_scanning? SecretScanning { get; set; }
        /// <summary>The enablement status of secret scanning push protection</summary>
        public WithConfiguration_PatchRequestBody_secret_scanning_push_protection? SecretScanningPushProtection { get; set; }
        /// <summary>The enablement status of secret scanning validity checks</summary>
        public WithConfiguration_PatchRequestBody_secret_scanning_validity_checks? SecretScanningValidityChecks { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="WithConfiguration_PatchRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static WithConfiguration_PatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new WithConfiguration_PatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"advanced_security", n => { AdvancedSecurity = n.GetEnumValue<WithConfiguration_PatchRequestBody_advanced_security>(); } },
                {"code_scanning_default_setup", n => { CodeScanningDefaultSetup = n.GetEnumValue<WithConfiguration_PatchRequestBody_code_scanning_default_setup>(); } },
                {"dependabot_alerts", n => { DependabotAlerts = n.GetEnumValue<WithConfiguration_PatchRequestBody_dependabot_alerts>(); } },
                {"dependabot_security_updates", n => { DependabotSecurityUpdates = n.GetEnumValue<WithConfiguration_PatchRequestBody_dependabot_security_updates>(); } },
                {"dependency_graph", n => { DependencyGraph = n.GetEnumValue<WithConfiguration_PatchRequestBody_dependency_graph>(); } },
                {"description", n => { Description = n.GetStringValue(); } },
                {"name", n => { Name = n.GetStringValue(); } },
                {"private_vulnerability_reporting", n => { PrivateVulnerabilityReporting = n.GetEnumValue<WithConfiguration_PatchRequestBody_private_vulnerability_reporting>(); } },
                {"secret_scanning", n => { SecretScanning = n.GetEnumValue<WithConfiguration_PatchRequestBody_secret_scanning>(); } },
                {"secret_scanning_push_protection", n => { SecretScanningPushProtection = n.GetEnumValue<WithConfiguration_PatchRequestBody_secret_scanning_push_protection>(); } },
                {"secret_scanning_validity_checks", n => { SecretScanningValidityChecks = n.GetEnumValue<WithConfiguration_PatchRequestBody_secret_scanning_validity_checks>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<WithConfiguration_PatchRequestBody_advanced_security>("advanced_security", AdvancedSecurity);
            writer.WriteEnumValue<WithConfiguration_PatchRequestBody_code_scanning_default_setup>("code_scanning_default_setup", CodeScanningDefaultSetup);
            writer.WriteEnumValue<WithConfiguration_PatchRequestBody_dependabot_alerts>("dependabot_alerts", DependabotAlerts);
            writer.WriteEnumValue<WithConfiguration_PatchRequestBody_dependabot_security_updates>("dependabot_security_updates", DependabotSecurityUpdates);
            writer.WriteEnumValue<WithConfiguration_PatchRequestBody_dependency_graph>("dependency_graph", DependencyGraph);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<WithConfiguration_PatchRequestBody_private_vulnerability_reporting>("private_vulnerability_reporting", PrivateVulnerabilityReporting);
            writer.WriteEnumValue<WithConfiguration_PatchRequestBody_secret_scanning>("secret_scanning", SecretScanning);
            writer.WriteEnumValue<WithConfiguration_PatchRequestBody_secret_scanning_push_protection>("secret_scanning_push_protection", SecretScanningPushProtection);
            writer.WriteEnumValue<WithConfiguration_PatchRequestBody_secret_scanning_validity_checks>("secret_scanning_validity_checks", SecretScanningValidityChecks);
        }
    }
}
