// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Octokit.Enterprises.Item.SecretScanning.Alerts {
    public enum GetStateQueryParameterType {
        [EnumMember(Value = "open")]
        Open,
        [EnumMember(Value = "resolved")]
        Resolved,
    }
}
