// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Octokit.Advisories {
    public enum GetDirectionQueryParameterType {
        [EnumMember(Value = "asc")]
        Asc,
        [EnumMember(Value = "desc")]
        Desc,
    }
}
