// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Users.Item.Repos {
    public enum GetDirectionQueryParameterType
    {
        [EnumMember(Value = "asc")]
        Asc,
        [EnumMember(Value = "desc")]
        Desc,
    }
}
