// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models {
    #pragma warning disable CS1591
    public enum ContentSubmodule_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "submodule")]
        #pragma warning disable CS1591
        Submodule,
        #pragma warning restore CS1591
    }
}
