// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models {
    /// <summary>The organization policy for allowing or disallowing organization members to use Copilot within their CLI.</summary>
    public enum CopilotOrganizationDetails_cli {
        [EnumMember(Value = "enabled")]
        Enabled,
        [EnumMember(Value = "disabled")]
        Disabled,
        [EnumMember(Value = "unconfigured")]
        Unconfigured,
    }
}
