// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models {
    #pragma warning disable CS1591
    public enum InstallationToken_repository_selection
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
        [EnumMember(Value = "selected")]
        #pragma warning disable CS1591
        Selected,
        #pragma warning restore CS1591
    }
}
