// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models
{
    /// <summary>The registry type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public enum OrgPrivateRegistryConfiguration_registry_type
    {
        [EnumMember(Value = "maven_repository")]
        #pragma warning disable CS1591
        Maven_repository,
        #pragma warning restore CS1591
    }
}
