// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace GitHub.Models {
    /// <summary>
    /// Choose which status checks must pass before the ref is updated. When enabled, commits must first be pushed to another ref where the checks pass.
    /// </summary>
    public class RepositoryRuleRequiredStatusChecks : IAdditionalDataHolder, IParsable 
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The parameters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RepositoryRuleRequiredStatusChecks_parameters? Parameters { get; set; }
#nullable restore
#else
        public RepositoryRuleRequiredStatusChecks_parameters Parameters { get; set; }
#endif
        /// <summary>The type property</summary>
        public RepositoryRuleRequiredStatusChecks_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="RepositoryRuleRequiredStatusChecks"/> and sets the default values.
        /// </summary>
        public RepositoryRuleRequiredStatusChecks()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="RepositoryRuleRequiredStatusChecks"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static RepositoryRuleRequiredStatusChecks CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new RepositoryRuleRequiredStatusChecks();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"parameters", n => { Parameters = n.GetObjectValue<RepositoryRuleRequiredStatusChecks_parameters>(RepositoryRuleRequiredStatusChecks_parameters.CreateFromDiscriminatorValue); } },
                {"type", n => { Type = n.GetEnumValue<RepositoryRuleRequiredStatusChecks_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<RepositoryRuleRequiredStatusChecks_parameters>("parameters", Parameters);
            writer.WriteEnumValue<RepositoryRuleRequiredStatusChecks_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
