// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models
{
    /// <summary>The permission associated with the invitation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public enum RepositoryInvitation_permissions
    {
        [EnumMember(Value = "read")]
        #pragma warning disable CS1591
        Read,
        #pragma warning restore CS1591
        [EnumMember(Value = "write")]
        #pragma warning disable CS1591
        Write,
        #pragma warning restore CS1591
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "triage")]
        #pragma warning disable CS1591
        Triage,
        #pragma warning restore CS1591
        [EnumMember(Value = "maintain")]
        #pragma warning disable CS1591
        Maintain,
        #pragma warning restore CS1591
    }
}
