// <auto-generated/>
using GitHub.Octokit.Models;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace GitHub.Octokit.Orgs.Item.Properties.Values {
    public class ValuesPatchRequestBody : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of custom property names and associated values to apply to the repositories.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<CustomPropertyValue>? Properties { get; set; }
#nullable restore
#else
        public List<CustomPropertyValue> Properties { get; set; }
#endif
        /// <summary>The names of repositories that the custom property values will be applied to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RepositoryNames { get; set; }
#nullable restore
#else
        public List<string> RepositoryNames { get; set; }
#endif
        /// <summary>
        /// Instantiates a new valuesPatchRequestBody and sets the default values.
        /// </summary>
        public ValuesPatchRequestBody() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ValuesPatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ValuesPatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"properties", n => { Properties = n.GetCollectionOfObjectValues<CustomPropertyValue>(CustomPropertyValue.CreateFromDiscriminatorValue)?.ToList(); } },
                {"repository_names", n => { RepositoryNames = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<CustomPropertyValue>("properties", Properties);
            writer.WriteCollectionOfPrimitiveValues<string>("repository_names", RepositoryNames);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
