// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Octokit.Repos.Item.Item.CheckRuns.Item {
    public enum WithCheck_run_PatchRequestBodyMember1_status {
        [EnumMember(Value = "completed")]
        Completed,
    }
}
