// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Octokit.Models {
    /// <summary>The leve of permission to grant the access token to manage Dependabot secrets.</summary>
    public enum AppPermissions_dependabot_secrets {
        [EnumMember(Value = "read")]
        Read,
        [EnumMember(Value = "write")]
        Write,
    }
}
