// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Octokit.Models {
    /// <summary>The phase of the lifecycle that the check is currently in.</summary>
    public enum CheckRun_status {
        [EnumMember(Value = "queued")]
        Queued,
        [EnumMember(Value = "in_progress")]
        In_progress,
        [EnumMember(Value = "completed")]
        Completed,
    }
}
