// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Octokit.Client.Models {
    /// <summary>State of a code scanning alert.</summary>
    public enum CodeScanningAlertStateQuery {
        [EnumMember(Value = "open")]
        Open,
        [EnumMember(Value = "closed")]
        Closed,
        [EnumMember(Value = "dismissed")]
        Dismissed,
        [EnumMember(Value = "fixed")]
        Fixed,
    }
}
