// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Octokit.Models {
    /// <summary>The reason that the alert was dismissed.</summary>
    public enum DependabotAlertWithRepository_dismissed_reason {
        [EnumMember(Value = "fix_started")]
        Fix_started,
        [EnumMember(Value = "inaccurate")]
        Inaccurate,
        [EnumMember(Value = "no_bandwidth")]
        No_bandwidth,
        [EnumMember(Value = "not_used")]
        Not_used,
        [EnumMember(Value = "tolerable_risk")]
        Tolerable_risk,
    }
}
