// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Octokit.Models {
    /// <summary>Type of repository selection requested.</summary>
    public enum OrganizationProgrammaticAccessGrantRequest_repository_selection {
        [EnumMember(Value = "none")]
        None,
        [EnumMember(Value = "all")]
        All,
        [EnumMember(Value = "subset")]
        Subset,
    }
}
