// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Octokit.Models {
    /// <summary>The target of the ruleset</summary>
    public enum RepositoryRuleset_target {
        [EnumMember(Value = "branch")]
        Branch,
        [EnumMember(Value = "tag")]
        Tag,
    }
}
