// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Octokit.User.Packages.Item.Item.Versions {
    public enum GetStateQueryParameterType {
        [EnumMember(Value = "active")]
        Active,
        [EnumMember(Value = "deleted")]
        Deleted,
    }
}
