// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Octokit.Orgs.Item.Teams.Item.Members {
    public enum GetRoleQueryParameterType {
        [EnumMember(Value = "member")]
        Member,
        [EnumMember(Value = "maintainer")]
        Maintainer,
        [EnumMember(Value = "all")]
        All,
    }
}
