// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Projects.Item.Collaborators
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    #pragma warning disable CS1591
    public enum GetAffiliationQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "outside")]
        #pragma warning disable CS1591
        Outside,
        #pragma warning restore CS1591
        [EnumMember(Value = "direct")]
        #pragma warning disable CS1591
        Direct,
        #pragma warning restore CS1591
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
    }
}
