// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Octokit.Repos.Item.Item.Forks {
    public enum GetSortQueryParameterType {
        [EnumMember(Value = "newest")]
        Newest,
        [EnumMember(Value = "oldest")]
        Oldest,
        [EnumMember(Value = "stargazers")]
        Stargazers,
        [EnumMember(Value = "watchers")]
        Watchers,
    }
}
