// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Octokit.Client.User.Repos {
    public enum GetVisibilityQueryParameterType {
        [EnumMember(Value = "all")]
        All,
        [EnumMember(Value = "public")]
        Public,
        [EnumMember(Value = "private")]
        Private,
    }
}
