// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Octokit.Repos.Item.Item.Issues.Item {
    /// <summary>The reason for the state change. Ignored unless `state` is changed.</summary>
    public enum WithIssue_numberPatchRequestBody_state_reason {
        [EnumMember(Value = "completed")]
        Completed,
        [EnumMember(Value = "not_planned")]
        Not_planned,
        [EnumMember(Value = "reopened")]
        Reopened,
    }
}
