// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Octokit.Client.Repos.Item.Item.Traffic.Clones {
    public enum GetPerQueryParameterType {
        [EnumMember(Value = "day")]
        Day,
        [EnumMember(Value = "week")]
        Week,
    }
}
