// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Orgs.Item.PersonalAccessTokenRequests
{
    /// <summary>Action to apply to the requests.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public enum PersonalAccessTokenRequestsPostRequestBody_action
    {
        [EnumMember(Value = "approve")]
        #pragma warning disable CS1591
        Approve,
        #pragma warning restore CS1591
        [EnumMember(Value = "deny")]
        #pragma warning disable CS1591
        Deny,
        #pragma warning restore CS1591
    }
}
