// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Repos.Item.Item.CheckRuns {
    #pragma warning disable CS1591
    public enum CheckRunsPostRequestBodyMember2_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "queued")]
        #pragma warning disable CS1591
        Queued,
        #pragma warning restore CS1591
        [EnumMember(Value = "in_progress")]
        #pragma warning disable CS1591
        In_progress,
        #pragma warning restore CS1591
    }
}
