// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Repos.Item.Item.CheckRuns {
    #pragma warning disable CS1591
    public enum CheckRunsPostRequestBodyMember1_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "completed")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
    }
}
