// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Octokit.Repos.Item.Item.Collaborators {
    public enum GetAffiliationQueryParameterType {
        [EnumMember(Value = "outside")]
        Outside,
        [EnumMember(Value = "direct")]
        Direct,
        [EnumMember(Value = "all")]
        All,
    }
}
