// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Repos.Item.Item.SecurityAdvisories {
    public enum GetSortQueryParameterType {
        [EnumMember(Value = "created")]
        Created,
        [EnumMember(Value = "updated")]
        Updated,
        [EnumMember(Value = "published")]
        Published,
    }
}
