name: Publish Release to NuGet

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.x.x
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build and strong name
      run: dotnet build --configuration Release --no-incremental -p:version=${GITHUB_REF#refs/*/v} -p:SignAssembly=true -p:AssemblyOriginatorKeyFile=../key.snk

    - name: Pack SDK
      run: dotnet pack -p:version=${GITHUB_REF#refs/*/v} -o ./publish

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./publish/*.nupkg --skip-duplicate
